/* Phase 14S booking-date, availability freshness and exact operational handoff. */
const tx=n=>String(n?.textContent||"").trim().replace(/\s+/g," ");
let dirty=false,pending=false,serial=0,deep=null,queued=false;
const prior=window.fetch.bind(window);
window.fetch=async(...args)=>{const i=args[0],u=typeof i==="string"?i:String(i?.url||""),match=/\/api\/admin\/bookings\/availability(?:\?|$)/.test(u),n=match?++serial:serial;if(match){pending=true;dirty=true;schedule()}try{return await prior(...args)}finally{if(match)setTimeout(()=>{if(n!==serial)return;pending=false;dirty=false;schedule()},90)}};
function addDay(iso){const [y,m,d]=String(iso||"").split("-").map(Number);if(!y||!m||!d)return"";const x=new Date(y,m-1,d);x.setDate(x.getDate()+1);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function today(){const x=new Date();return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function setInput(i,v){if(!(i instanceof HTMLInputElement)||i.value===v)return;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(i,v);i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))}
function label(i){const l=i.closest("label");return l?[...l.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent||"").join(" ").trim().toLowerCase():""}
function dates(){const f=document.querySelector(".booking-layout .booking-form");if(!f)return;const a=[...f.querySelectorAll('input[type="date"]')],p=a.find(i=>label(i).startsWith("pickup date")),r=a.find(i=>label(i).startsWith("return date"));if(!p||!r)return;if(!p.value)setInput(p,today());const min=addDay(p.value);if(!min)return;r.min=min;if(!r.value||r.value<min)setInput(r,min)}
function selected(){return[...document.querySelectorAll(".booking-line select")].some(s=>!!s.value)}
function fresh(){const wait=selected()&&(dirty||pending);if(!selected()&&!pending)dirty=false;document.querySelectorAll(".booking-line").forEach(l=>{const s=l.querySelector("select"),p=l.querySelector(".availability-pill");if(wait&&s?.value&&p){p.classList.remove("bad");p.classList.add("phase14s-checking");p.textContent="Checking…"}else p?.classList.remove("phase14s-checking")});document.querySelectorAll(".phase14r-picker-copy em").forEach(n=>{if(tx(n)!=="Already selected")n.textContent="Select to check exact availability"})}
function setControlled(i,v){if(!(i instanceof HTMLInputElement))return;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(i,v);i.dispatchEvent(new Event("input",{bubbles:true}));i.dispatchEvent(new Event("change",{bubbles:true}))}
function start(panel,destination){const bookingNo=tx(panel.querySelector(".history-title h2"));if(!bookingNo)return;deep={bookingNo,destination,started:Date.now(),stage:"none",opened:false};panel.querySelector(".history-title button")?.click();[...document.querySelectorAll(".tabs button")].find(b=>tx(b)===destination)?.click();schedule()}
function openExact(){if(!deep||deep.opened)return;if(Date.now()-deep.started>12000){deep=null;return}if(tx(document.querySelector(".page-head h1"))!==deep.destination)return;const sel=deep.destination==="Pickup"?".pickup-card:not(.return-card)":".return-card";const card=[...document.querySelectorAll(sel)].find(c=>tx(c.querySelector(".booking-card-head strong"))===deep.bookingNo);if(card){const b=[...card.querySelectorAll("button")].find(x=>/^(Open Pickup|Open Return|View)$/i.test(tx(x)));if(b&&!b.disabled){deep.opened=true;card.classList.add("phase14s-deep-link-hit");setTimeout(()=>b.click(),60);setTimeout(()=>deep=null,500)}return}if([...document.querySelectorAll(".empty")].some(n=>/^Loading/i.test(tx(n))))return;const search=document.querySelector(".pickup-search input"),all=[...document.querySelectorAll(".pickup-tabs button")].find(b=>tx(b)==="All");if(!search||!all)return;if(deep.stage==="none"){deep.stage="prepared";setControlled(search,deep.bookingNo);setTimeout(()=>{if(!deep)return;if(all.classList.contains("active")){deep.stage="search";document.querySelector(".pickup-search button")?.click()}else{deep.stage="all";all.click()}},90);return}if(deep.stage==="all"){deep.stage="search";setControlled(search,deep.bookingNo);setTimeout(()=>document.querySelector(".pickup-search button")?.click(),60)}}
function scan(){queued=false;dates();fresh();openExact()}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(scan)}
document.addEventListener("change",e=>{const x=e.target;if(e.isTrusted&&x instanceof HTMLInputElement&&x.type==="date"&&x.closest(".booking-layout")){dates();dirty=selected();schedule()}if(e.isTrusted&&x instanceof HTMLSelectElement&&x.closest(".booking-line")){dirty=true;schedule()}},true);
document.addEventListener("click",e=>{const x=e.target instanceof Element?e.target:null,b=x?.closest("button");if(!b)return;if(b.closest(".phase14r-context-actions")&&/^(Go to Pickup|Go to Returns)$/i.test(tx(b))){const p=b.closest(".history-panel.booking-detail");if(p){e.preventDefault();e.stopImmediatePropagation();start(p,/Pickup/i.test(tx(b))?"Pickup":"Returns");return}}if(b.closest(".phase14r-picker-card")||/Add Another Item|Remove item/i.test(`${tx(b)} ${b.getAttribute("aria-label")||""}`)){dirty=true;schedule()}},true);
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();