/* Phase 14T core continuity: broader unsaved guards + session continuity. */
const C=n=>String(n?.textContent||"").trim().replace(/\s+/g," ");
const CF='button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
const cDirty=new Set();let cBypass=false,cPending=null,cPendingKinds=[],cAwaiting=null,cLastFeedback="",cLastModule="",cQueued=false,cScrollTimer=0;
const cModule=()=>C(document.querySelector(".page-head h1"))||"Dashboard";
const cOp=()=>cModule()==="Pickup"?"pickup":cModule()==="Returns"?"returns":"";
function cKind(x){if(!(x instanceof Element))return"";if(x.closest(".manage-grid form,.field-form"))return"categories";if(x.closest(".settings-section")&&!x.closest(".audit-filters"))return"settings";if(x.closest(".history-panel.pickup-panel"))return cOp();return""}
function cSync(){document.body.classList.toggle("phase14t-unsaved",cDirty.size>0)}
function cMark(k){if(k){cDirty.add(k);cSync()}} function cClear(k){k?cDirty.delete(k):cDirty.clear();cSync()}
function cDialog(){let b=document.querySelector(".phase14t-guard-backdrop");if(b)return b;b=document.createElement("div");b.className="phase14t-guard-backdrop";const d=document.createElement("section");d.className="phase14t-guard-dialog";d.setAttribute("role","dialog");d.setAttribute("aria-modal","true");d.innerHTML='<div class="phase14t-guard-icon">!</div><h2>Discard unsaved work?</h2><p>This screen has changes that have not been saved yet.</p><div class="phase14t-guard-actions"><button type="button" class="ghost phase14t-keep">Keep Editing</button><button type="button" class="phase14t-discard">Discard & Continue</button></div>';b.appendChild(d);document.body.appendChild(b);const hide=()=>{b.classList.remove("open");cPending=null;cPendingKinds=[]};b.addEventListener("click",e=>{if(e.target===b)hide()});d.querySelector(".phase14t-keep")?.addEventListener("click",hide);d.querySelector(".phase14t-discard")?.addEventListener("click",()=>{const a=cPending,ks=[...cPendingKinds];cPending=null;cPendingKinds=[];b.classList.remove("open");ks.forEach(cClear);cBypass=true;try{a?.()}finally{setTimeout(()=>cBypass=false,0)}});return b}
function cGuard(action,kinds=[...cDirty]){const ks=kinds.filter(k=>cDirty.has(k));if(cBypass||!ks.length){action();return}const b=cDialog();cPending=action;cPendingKinds=ks;b.classList.add("open");setTimeout(()=>b.querySelector(".phase14t-keep")?.focus(),0)}
function cTrap(e){const d=document.querySelector(".phase14t-guard-backdrop.open .phase14t-guard-dialog");if(!d||e.key!=="Tab")return;const a=[...d.querySelectorAll(CF)].filter(x=>x instanceof HTMLElement&&x.getClientRects().length);if(!a.length)return;const f=a[0],l=a.at(-1);if(e.shiftKey&&document.activeElement===f){e.preventDefault();l.focus()}else if(!e.shiftKey&&document.activeElement===l){e.preventDefault();f.focus()}}
function cSearch(){if(cModule()==="Reports")return document.querySelector(".report-search input");return[...document.querySelectorAll(".list-card input")].find(i=>i instanceof HTMLInputElement&&["","text","search"].includes(i.type)&&/search|booking|customer|mobile|item|name|code/i.test(i.placeholder||""))||null}
const cSearchKey=()=>`zhagmag:phase14t:search:${cModule()}`;
function cRemember(i){if(i!==cSearch())return;const v=i.value.trim();try{v?sessionStorage.setItem(cSearchKey(),v):sessionStorage.removeItem(cSearchKey())}catch{}}
/* Search memory stays internal. Legacy visible restore controls are removed instead of injected. */
function cRestoreSearch(){document.querySelectorAll(".phase14t-restore-query").forEach(node=>node.remove())}
const cScrollKey=(m=cModule())=>`zhagmag:phase14t:scroll:${m}`;
addEventListener("scroll",()=>{clearTimeout(cScrollTimer);cScrollTimer=setTimeout(()=>{try{sessionStorage.setItem(cScrollKey(),String(Math.max(0,Math.round(scrollY))))}catch{}},120)},{passive:true});
function cRestoreScroll(m){let y=0;try{y=Number(sessionStorage.getItem(cScrollKey(m))||0)}catch{}if(!Number.isFinite(y)||y<=0)return;setTimeout(()=>scrollTo({top:y,behavior:"auto"}),120);setTimeout(()=>scrollTo({top:y,behavior:"auto"}),520)}
function cFeedbackKind(){const m=cModule();return m==="Categories & Custom Fields"?"categories":m==="Settings"?"settings":m==="Pickup"?"pickup":m==="Returns"?"returns":""}
function cFeedback(){const ok=C(document.querySelector(".page-message.message.success")),er=C(document.querySelector(".page-message.message.error")),sig=`${cModule()}|${ok}|${er}`;if(sig===cLastFeedback)return;cLastFeedback=sig;if(er&&cAwaiting)cAwaiting=null;const k=cFeedbackKind();if(ok&&k&&cAwaiting===k){cClear(k);cAwaiting=null}}
function cScan(){cQueued=false;const m=cModule();if(m&&m!==cLastModule){cLastModule=m;cRestoreScroll(m)}cRestoreSearch();cFeedback()}
function cSchedule(){if(cQueued)return;cQueued=true;requestAnimationFrame(cScan)}
document.addEventListener("input",e=>{if(!e.isTrusted)return;cMark(cKind(e.target));if(e.target instanceof HTMLInputElement)cRemember(e.target);cSchedule()},true);
document.addEventListener("change",e=>{if(e.isTrusted){cMark(cKind(e.target));cSchedule()}},true);
document.addEventListener("submit",e=>{const f=e.target;if(!(f instanceof HTMLFormElement))return;if(f.closest(".manage-grid,.field-form"))cAwaiting="categories";if(f.closest(".template-editor"))cAwaiting="settings"},true);
document.addEventListener("click",e=>{const x=e.target instanceof Element?e.target:null,b=x?.closest("button");if(!x)return;if(b?.matches(".phase14s-discard")){cClear();return}if(e.isTrusted&&b?.matches(".tabs button,.topbar .profile")&&cDirty.size&&!cBypass){try{sessionStorage.setItem(cScrollKey(),String(Math.max(0,Math.round(scrollY))))}catch{}e.preventDefault();e.stopImmediatePropagation();cGuard(()=>b.click());return}const k=cKind(x);if(e.isTrusted&&cModule()==="Categories & Custom Fields"&&b&&cDirty.has("categories")&&!cBypass&&(/^(Cancel|Close Fields)$/i.test(C(b))||!!b.closest(".category-list")&&/^(Fields|Edit|\+ Add Field)$/i.test(C(b)))){e.preventDefault();e.stopImmediatePropagation();cGuard(()=>b.click(),["categories"]);return}if(e.isTrusted&&k==="settings"&&b&&/^Clear$/i.test(C(b))&&cDirty.has(k)&&!cBypass){e.preventDefault();e.stopImmediatePropagation();cGuard(()=>b.click(),[k]);return}const ok=cOp(),p=x.closest(".history-panel.pickup-panel");if(e.isTrusted&&ok&&p&&b&&/^Close$/i.test(C(b))&&cDirty.has(ok)&&!cBypass){e.preventDefault();e.stopImmediatePropagation();cGuard(()=>b.click(),[ok]);return}if(e.isTrusted&&ok&&x.matches(".history-backdrop")&&x.querySelector(":scope > .history-panel.pickup-panel")&&cDirty.has(ok)&&!cBypass){e.preventDefault();e.stopImmediatePropagation();cGuard(()=>x.click(),[ok]);return}if(e.isTrusted&&ok&&b&&/^(Give All Remaining|Return All Pending)$/i.test(C(b)))cMark(ok);if(b&&/^(Save Pickup|Save Return|Save Correction)$/i.test(C(b))&&p)cAwaiting=ok;if(b&&/^Save (Settings|Public Controls)$/i.test(C(b)))cAwaiting="settings"},true);
document.addEventListener("keydown",e=>{cTrap(e);if(e.key!=="Escape")return;const g=document.querySelector(".phase14t-guard-backdrop.open");if(g){e.preventDefault();e.stopImmediatePropagation();g.classList.remove("open");cPending=null;cPendingKinds=[];return}const k=cOp(),p=document.querySelector(".history-panel.pickup-panel");if(k&&p&&cDirty.has(k)&&!cBypass){e.preventDefault();e.stopImmediatePropagation();const close=[...p.querySelectorAll(".history-title button")].find(b=>/^Close$/i.test(C(b)));cGuard(()=>close?.click(),[k])}},true);
addEventListener("beforeunload",e=>{if(cDirty.size){e.preventDefault();e.returnValue=""}});
new MutationObserver(cSchedule).observe(document.documentElement,{childList:true,subtree:true});cSchedule();
