/* Phase 14S navigation + modal reliability. */
const t=n=>String(n?.textContent||"").trim().replace(/\s+/g," ");
const focusable='button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
let bypass=false,pending=null,userDirty=false,passwordDirty=false;
function hasUnsaved(){return document.body.classList.contains("phase14r-unsaved")||userDirty||passwordDirty}
function ensureDialog(){let b=document.querySelector(".phase14s-nav-backdrop");if(b)return b;b=document.createElement("div");b.className="phase14s-nav-backdrop";const d=document.createElement("section");d.className="phase14s-nav-dialog";d.setAttribute("role","dialog");d.setAttribute("aria-modal","true");d.setAttribute("aria-labelledby","phase14s-nav-title");d.innerHTML='<div class="phase14s-nav-icon">!</div><h2 id="phase14s-nav-title">Leave without saving?</h2><p>You have unsaved changes. Continue editing or discard them before leaving this screen.</p><div class="phase14s-nav-actions"><button type="button" class="ghost phase14s-keep">Keep Editing</button><button type="button" class="phase14s-discard">Discard & Continue</button></div>';b.appendChild(d);document.body.appendChild(b);const hide=()=>{b.classList.remove("open");pending=null};b.addEventListener("click",e=>{if(e.target===b)hide()});d.querySelector(".phase14s-keep")?.addEventListener("click",hide);d.querySelector(".phase14s-discard")?.addEventListener("click",()=>{const a=pending;pending=null;b.classList.remove("open");userDirty=false;passwordDirty=false;bypass=true;try{a?.()}finally{setTimeout(()=>bypass=false,0)}});return b}
function guard(action){if(bypass||!hasUnsaved()){action();return}const b=ensureDialog();pending=action;b.classList.add("open");setTimeout(()=>b.querySelector(".phase14s-keep")?.focus(),0)}
function closeModal(modal){[...modal.querySelectorAll("button")].find(b=>/^Close$/i.test(t(b)))?.click()}
function dirtyTarget(target){if(!(target instanceof Element))return;if(target.closest(".user-modal"))userDirty=true;if(target.closest(".password-modal"))passwordDirty=true}
function syncDirty(){if(!document.querySelector(".user-modal"))userDirty=false;if(!document.querySelector(".password-modal"))passwordDirty=false}
function visibleModal(){const selectors=[".phase14s-nav-dialog",".phase14r-item-picker",".phase14r-discard-dialog",".user-modal",".password-modal"];return selectors.flatMap(s=>[...document.querySelectorAll(s)]).filter(n=>n instanceof HTMLElement&&n.getClientRects().length).at(-1)||null}
function trapTab(e){if(e.key!=="Tab")return;const m=visibleModal();if(!m)return;const f=[...m.querySelectorAll(focusable)].filter(n=>n instanceof HTMLElement&&n.getClientRects().length);if(!f.length){e.preventDefault();m.tabIndex=-1;m.focus();return}const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
function focusNew(){document.querySelectorAll(".user-modal,.password-modal").forEach(m=>{if(m.dataset.phase14sFocus)return;m.dataset.phase14sFocus="1";setTimeout(()=>m.querySelector("input,select,textarea,button")?.focus(),0)})}
document.addEventListener("input",e=>{if(e.isTrusted)dirtyTarget(e.target)},true);document.addEventListener("change",e=>{if(e.isTrusted)dirtyTarget(e.target)},true);
document.addEventListener("click",e=>{const x=e.target instanceof Element?e.target:null,b=x?.closest("button");if(!b)return;if(((b.matches(".tabs button")&&!b.classList.contains("active"))||b.matches(".topbar .profile"))&&!bypass&&hasUnsaved()){e.preventDefault();e.stopImmediatePropagation();guard(()=>b.click());return}const um=b.closest(".user-modal"),pm=b.closest(".password-modal");if(um&&/^Close$/i.test(t(b))&&userDirty&&!bypass){e.preventDefault();e.stopImmediatePropagation();guard(()=>closeModal(um));return}if(pm&&/^Close$/i.test(t(b))&&passwordDirty&&!bypass){e.preventDefault();e.stopImmediatePropagation();guard(()=>closeModal(pm))}},true);
document.addEventListener("click",e=>{const x=e.target instanceof Element?e.target:null;if(!x?.matches(".history-backdrop")||bypass)return;const um=x.querySelector(":scope > .user-modal"),pm=x.querySelector(":scope > .password-modal");if(um&&userDirty){e.preventDefault();e.stopImmediatePropagation();guard(()=>{userDirty=false;bypass=true;try{x.click()}finally{bypass=false}})}else if(pm&&passwordDirty){e.preventDefault();e.stopImmediatePropagation();guard(()=>{passwordDirty=false;bypass=true;try{x.click()}finally{bypass=false}})}},true);
document.addEventListener("keydown",e=>{trapTab(e);if(e.key!=="Escape")return;if(document.querySelector(".phase14s-nav-backdrop.open")){e.preventDefault();e.stopImmediatePropagation();document.querySelector(".phase14s-nav-backdrop")?.classList.remove("open");pending=null;return}const um=document.querySelector(".user-modal"),pm=document.querySelector(".password-modal");if(um){e.preventDefault();e.stopImmediatePropagation();userDirty?guard(()=>closeModal(um)):closeModal(um);return}if(pm){e.preventDefault();e.stopImmediatePropagation();passwordDirty?guard(()=>closeModal(pm)):closeModal(pm)}},true);
window.addEventListener("beforeunload",e=>{if(userDirty||passwordDirty){e.preventDefault();e.returnValue=""}});new MutationObserver(()=>{syncDirty();focusNew()}).observe(document.documentElement,{childList:true,subtree:true});syncDirty();focusNew();