const KEY="zhagmag.booking.prefillCustomer";
let form=null,formObserver=null,select=null,selectObserver=null,queued=false;
const digits=v=>String(v||"").replace(/\D/g,"");
const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;sync()})};
function nativeSelect(el,value){Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,"value")?.set?.call(el,value);el.dispatchEvent(new Event("change",{bubbles:true}))}
function nativeInput(el,value){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(el,value);el.dispatchEvent(new Event("input",{bubbles:true}))}
function pending(){try{const v=JSON.parse(sessionStorage.getItem(KEY)||"null"),mobile=digits(v?.mobile);return mobile?{name:String(v?.name||""),mobile}:null}catch{return null}}
function savePending(card){const name=String(card.querySelector(".customer-head strong")?.textContent||"").trim(),mobile=digits(card.querySelector('.customer-head a[href^="tel:"]')?.getAttribute("href"));if(!mobile)return false;try{sessionStorage.setItem(KEY,JSON.stringify({name,mobile}))}catch{}return true}
function bookingTab(){const tabs=[...document.querySelectorAll(".tabs button")];return tabs.find(b=>b.dataset.phase14arSource==="Bookings")||tabs.find(b=>String(b.textContent||"").trim()==="Bookings")||tabs.find(b=>b.classList.contains("active"))?.nextElementSibling||null}
document.addEventListener("click",e=>{const t=e.target instanceof Element?e.target.closest(".phase14as-create-booking"):null;if(!(t instanceof HTMLButtonElement))return;const card=t.closest(".customer-card");if(!card||!savePending(card))return;e.preventDefault();e.stopImmediatePropagation();requestAnimationFrame(()=>{const tab=bookingTab();if(tab instanceof HTMLButtonElement){tab.click();requestAnimationFrame(schedule);window.setTimeout(()=>{if(!document.querySelector(".booking-form")&&tab.isConnected)tab.click()},760)}})},true);
function parts(){const f=document.querySelector(".booking-form");if(!(f instanceof HTMLFormElement))return null;const picker=f.querySelector(".customer-picker"),input=picker?.querySelector("input"),sel=[...f.querySelectorAll("select")].find(s=>!s.closest(".booking-lines"));return picker instanceof HTMLElement&&input instanceof HTMLInputElement&&sel instanceof HTMLSelectElement?{f,picker,input,sel}:null}
function panelFor(picker){const f=picker.closest(".booking-form");let p=f?.querySelector(".phase14as-customer-results");if(!(p instanceof HTMLElement)){p=document.createElement("div");p.className="phase14as-customer-results";p.hidden=true;p.setAttribute("role","listbox");picker.insertAdjacentElement("afterend",p)}return p}
function info(o){const text=String(o.textContent||"").trim(),a=text.split(" · ").map(x=>x.trim()).filter(Boolean);return{text,name:a.length>1?a.slice(0,-1).join(" · "):text,mobile:a.length>1?a.at(-1)||"":""}}
function render(input,sel,p){const q=input.value.trim();if(q.length<2){p.hidden=true;p.replaceChildren();return}const low=q.toLocaleLowerCase(),num=digits(q),rows=[...sel.options].filter(o=>o.value).filter(o=>{const x=info(o).text;return x.toLocaleLowerCase().includes(low)||(num&&digits(x).includes(num))}).slice(0,10);p.replaceChildren();if(!rows.length){const d=document.createElement("div");d.className="phase14as-customer-empty";d.textContent="Searching / no matching customer yet…";p.append(d)}else rows.forEach(o=>{const x=info(o),b=document.createElement("button"),n=document.createElement("span"),m=document.createElement("small");b.type="button";b.className="phase14as-customer-result";n.textContent=x.name||"Customer";m.textContent=x.mobile;b.append(n,m);b.onclick=()=>{nativeSelect(sel,o.value);nativeInput(input,"");p.hidden=true;p.replaceChildren()};p.append(b)});p.hidden=false}
function bind(f,sel){if(f!==form){formObserver?.disconnect();form=f;formObserver=new MutationObserver(ms=>{if(ms.some(m=>m.target instanceof HTMLSelectElement||[...m.addedNodes,...m.removedNodes].some(n=>n instanceof Element&&Boolean(n.matches("select")||n.querySelector("select")))))schedule()});formObserver.observe(f,{childList:true,subtree:true})}if(sel!==select){selectObserver?.disconnect();select=sel;selectObserver=new MutationObserver(schedule);selectObserver.observe(sel,{childList:true})}}
function applyPending(input,sel){const x=pending();if(!x)return;const o=[...sel.options].find(v=>v.value&&digits(v.textContent).includes(x.mobile));if(o){nativeSelect(sel,o.value);try{sessionStorage.removeItem(KEY)}catch{};return}if(input.dataset.phase14asFix2Prefill!==x.mobile){input.dataset.phase14asFix2Prefill=x.mobile;nativeInput(input,x.mobile)}}
function sync(){const x=parts();if(!x)return;const p=panelFor(x.picker);bind(x.f,x.sel);if(x.input.dataset.phase14asFix2!=="1"){x.input.dataset.phase14asFix2="1";x.input.addEventListener("input",schedule);x.input.addEventListener("focus",schedule)}applyPending(x.input,x.sel);render(x.input,x.sel,p)}
const root=document.getElementById("root");if(root)new MutationObserver(schedule).observe(root,{childList:true});window.addEventListener("phase14ar-admin-ready",schedule);requestAnimationFrame(schedule);
