-- Phase 14BM: status-group WhatsApp template defaults.
-- Status-group membership is centralized in worker/src/whatsapp-template-registry.ts.

INSERT OR IGNORE INTO whatsapp_templates
  (id,template_key,template_name,message_text,is_active,message_gu,message_en,language_mode,linked_action)
VALUES
  ('tpl_reservation_reminder','reservation_reminder','Reservation Reminder',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે તમારું reservation ચાલુ છે. Pickup: {{pickup_date}}, Return: {{return_date}}. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે તમારું reservation ચાલુ છે. Pickup: {{pickup_date}}, Return: {{return_date}}. — {{business_name}}',
   'Hello {{customer_name}}, your reservation for booking {{booking_id}} is active. Pickup: {{pickup_date}}, Return: {{return_date}}. — {{business_name}}',
   'ALL','RESERVATION_REMINDER'),
  ('tpl_reservation_expiry_reminder','reservation_expiry_reminder','Reservation Expiry Reminder',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} reservation માટે કૃપા કરીને pickup તારીખ {{pickup_date}} પહેલાં સંપર્ક કરો. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} reservation માટે કૃપા કરીને pickup તારીખ {{pickup_date}} પહેલાં સંપર્ક કરો. — {{business_name}}',
   'Hello {{customer_name}}, please contact us before the pickup date {{pickup_date}} for reservation {{booking_id}}. — {{business_name}}',
   'ALL','RESERVATION_EXPIRY_REMINDER'),
  ('tpl_booking_details','booking_details','Booking Details',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} વિગતો: {{items}}. Pickup: {{pickup_date}}, Return: {{return_date}}, Status: {{status}}. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} વિગતો: {{items}}. Pickup: {{pickup_date}}, Return: {{return_date}}, Status: {{status}}. — {{business_name}}',
   'Hello {{customer_name}}, booking {{booking_id}} details: {{items}}. Pickup: {{pickup_date}}, Return: {{return_date}}, Status: {{status}}. — {{business_name}}',
   'ALL','BOOKING_DETAILS'),
  ('tpl_return_date_time_update','return_date_time_update','Return Date/Time Update',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે Return તારીખ {{return_date}} છે. કૃપા કરીને સમય અંગે જરૂર હોય તો અમારો સંપર્ક કરો. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે Return તારીખ {{return_date}} છે. કૃપા કરીને સમય અંગે જરૂર હોય તો અમારો સંપર્ક કરો. — {{business_name}}',
   'Hello {{customer_name}}, the return date for booking {{booking_id}} is {{return_date}}. Please contact us if you need a timing update. — {{business_name}}',
   'ALL','RETURN_DATE_TIME_UPDATE'),
  ('tpl_return_thank_you','return_thank_you','Return Thank You',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} નું return પૂર્ણ કરવા બદલ આભાર. ફરી સેવા આપવાની તક મળશે તેવી આશા. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} નું return પૂર્ણ કરવા બદલ આભાર. ફરી સેવા આપવાની તક મળશે તેવી આશા. — {{business_name}}',
   'Hello {{customer_name}}, thank you for completing the return for booking {{booking_id}}. We look forward to serving you again. — {{business_name}}',
   'ALL','RETURN_THANK_YOU'),
  ('tpl_feedback_review','feedback_review','Feedback / Review',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે આપનો અનુભવ અમને જણાવશો. આપનો feedback અમારે માટે મહત્વનો છે. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} માટે આપનો અનુભવ અમને જણાવશો. આપનો feedback અમારે માટે મહત્વનો છે. — {{business_name}}',
   'Hello {{customer_name}}, we would appreciate your feedback about booking {{booking_id}}. Thank you for helping us improve. — {{business_name}}',
   'ALL','FEEDBACK_REVIEW'),
  ('tpl_overdue_urgent_reminder','overdue_urgent_reminder','Urgent Reminder',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} નું return {{overdue_days}} દિવસથી overdue છે. બાકી જથ્થો: {{pending_qty}}. કૃપા કરીને તરત સંપર્ક કરો. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} નું return {{overdue_days}} દિવસથી overdue છે. બાકી જથ્થો: {{pending_qty}}. કૃપા કરીને તરત સંપર્ક કરો. — {{business_name}}',
   'Hello {{customer_name}}, return for booking {{booking_id}} is overdue by {{overdue_days}} day(s). Pending quantity: {{pending_qty}}. Please contact us urgently. — {{business_name}}',
   'ALL','OVERDUE_URGENT_REMINDER'),
  ('tpl_overdue_follow_up_reminder','overdue_follow_up_reminder','Follow-up Reminder',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} ના overdue return માટે આ follow-up છે. બાકી જથ્થો: {{pending_qty}}. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} ના overdue return માટે આ follow-up છે. બાકી જથ્થો: {{pending_qty}}. — {{business_name}}',
   'Hello {{customer_name}}, this is a follow-up for the overdue return on booking {{booking_id}}. Pending quantity: {{pending_qty}}. — {{business_name}}',
   'ALL','OVERDUE_FOLLOW_UP_REMINDER'),
  ('tpl_cancellation_details','cancellation_details','Cancellation Details',
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} cancel થયું છે. Booking status: {{status}}. Items: {{items}}. — {{business_name}}',
   1,
   'નમસ્તે {{customer_name}}, Booking {{booking_id}} cancel થયું છે. Booking status: {{status}}. Items: {{items}}. — {{business_name}}',
   'Hello {{customer_name}}, booking {{booking_id}} has been cancelled. Status: {{status}}. Items: {{items}}. — {{business_name}}',
   'ALL','CANCELLATION_DETAILS'),
  ('tpl_shop_address','shop_address','Shop Address',
   'નમસ્તે {{customer_name}}, {{business_name}} નું સરનામું: {{shop_address}}. સંપર્ક: {{shop_phone}}.',
   1,
   'નમસ્તે {{customer_name}}, {{business_name}} નું સરનામું: {{shop_address}}. સંપર્ક: {{shop_phone}}.',
   'Hello {{customer_name}}, {{business_name}} address: {{shop_address}}. Contact: {{shop_phone}}.',
   'ALL','SHOP_ADDRESS'),
  ('tpl_working_hours','working_hours','Working Hours',
   'નમસ્તે {{customer_name}}, {{business_name}} ના આજના working hours જાણવા માટે {{shop_phone}} અથવા {{shop_whatsapp}} પર સંપર્ક કરો.',
   1,
   'નમસ્તે {{customer_name}}, {{business_name}} ના આજના working hours જાણવા માટે {{shop_phone}} અથવા {{shop_whatsapp}} પર સંપર્ક કરો.',
   'Hello {{customer_name}}, please contact {{shop_phone}} or {{shop_whatsapp}} for today''s working hours at {{business_name}}.',
   'ALL','WORKING_HOURS'),
  ('tpl_holiday_shop_closed','holiday_shop_closed','Holiday / Shop Closed',
   'નમસ્તે {{customer_name}}, {{business_name}} આજે બંધ હોઈ શકે છે. મુલાકાત પહેલાં {{shop_phone}} પર સંપર્ક કરો.',
   1,
   'નમસ્તે {{customer_name}}, {{business_name}} આજે બંધ હોઈ શકે છે. મુલાકાત પહેલાં {{shop_phone}} પર સંપર્ક કરો.',
   'Hello {{customer_name}}, {{business_name}} may be closed today. Please contact {{shop_phone}} before visiting.',
   'ALL','HOLIDAY_SHOP_CLOSED'),
  ('tpl_contact_us','contact_us','Contact Us',
   'નમસ્તે {{customer_name}}, {{business_name}} સંપર્ક: Call {{shop_phone}}, WhatsApp {{shop_whatsapp}}, Address {{shop_address}}.',
   1,
   'નમસ્તે {{customer_name}}, {{business_name}} સંપર્ક: Call {{shop_phone}}, WhatsApp {{shop_whatsapp}}, Address {{shop_address}}.',
   'Hello {{customer_name}}, contact {{business_name}}: Call {{shop_phone}}, WhatsApp {{shop_whatsapp}}, Address {{shop_address}}.',
   'ALL','CONTACT_US'),
  ('tpl_custom_general_message','custom_general_message','Custom General Message',
   'નમસ્તે {{customer_name}}, {{business_name}} તરફથી સંદેશ. વધુ માહિતી માટે {{shop_whatsapp}} પર સંપર્ક કરો.',
   1,
   'નમસ્તે {{customer_name}}, {{business_name}} તરફથી સંદેશ. વધુ માહિતી માટે {{shop_whatsapp}} પર સંપર્ક કરો.',
   'Hello {{customer_name}}, a message from {{business_name}}. Contact us on {{shop_whatsapp}} for more information.',
   'ALL','CUSTOM_GENERAL_MESSAGE');

CREATE INDEX IF NOT EXISTS ix_whatsapp_templates_phase14bm_actions
  ON whatsapp_templates(linked_action,is_active,template_name);
