export const BOOKING_STATUS = {
  BOOKED: "BOOKED",
  PARTIALLY_GIVEN: "PARTIALLY_GIVEN",
  GIVEN: "GIVEN",
  PARTIALLY_RETURNED: "PARTIALLY_RETURNED",
  RETURNED: "RETURNED",
  CANCELLED: "CANCELLED"
} as const;

export const USER_ROLE = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  STAFF: "STAFF"
} as const;

export const FIELD_TYPE = {
  TEXT: "TEXT",
  NUMBER: "NUMBER",
  DROPDOWN: "DROPDOWN",
  MULTI_SELECT: "MULTI_SELECT",
  YES_NO: "YES_NO",
  DATE: "DATE"
} as const;

export const PERMISSION = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  CATEGORY_MANAGE: "CATEGORY_MANAGE",
  ITEM_VIEW: "ITEM_VIEW",
  ITEM_MANAGE: "ITEM_MANAGE",
  CUSTOMER_MANAGE: "CUSTOMER_MANAGE",
  BOOKING_MANAGE: "BOOKING_MANAGE",
  PICKUP_MANAGE: "PICKUP_MANAGE",
  RETURN_MANAGE: "RETURN_MANAGE",
  REPORT_VIEW: "REPORT_VIEW",
  USER_MANAGE: "USER_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
  AUDIT_VIEW: "AUDIT_VIEW"
} as const;

export type UserRole = typeof USER_ROLE[keyof typeof USER_ROLE];
export type Permission = typeof PERMISSION[keyof typeof PERMISSION];

const ALL_PERMISSIONS = Object.values(PERMISSION) as Permission[];

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  OWNER: ALL_PERMISSIONS,
  ADMIN: ALL_PERMISSIONS,
  STAFF: [
    PERMISSION.DASHBOARD_VIEW,
    PERMISSION.ITEM_VIEW,
    PERMISSION.CUSTOMER_MANAGE,
    PERMISSION.BOOKING_MANAGE,
    PERMISSION.PICKUP_MANAGE,
    PERMISSION.RETURN_MANAGE,
    PERMISSION.REPORT_VIEW
  ]
};
